spring:
  application:
    name: cv-api-gateway

  cloud:
    config:
      uri: http://103.168.18.176:8061

  profiles:
    active: default

  config:
    import: optional:configserver:${spring.cloud.config.uri}